<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(NevmDepsRoot)Nethermind.Core/Nethermind.Core.csproj" />
    <ProjectReference Include="$(NevmDepsRoot)Nethermind.Crypto/Nethermind.Crypto.csproj" />
    <ProjectReference Include="$(NevmDepsRoot)Nethermind.Serialization.Rlp/Nethermind.Serialization.Rlp.csproj" />
    <ProjectReference Include="$(NevmDepsRoot)Nethermind.Specs/Nethermind.Specs.csproj" />
  </ItemGroup>
</Project>
